version: "3"
services:
  # server:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - .:/usr/src/cnes-graphql
  prisma:
    image: prismagraphql/prisma:1.26.5
    # restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            database: paciente
            uri: >-
              mongodb+srv://yasser:emfYFwZptnSnYfQu@cluster1-7x4na.mongodb.net/test?retryWrites=true&w=majority
